### ISSUE TITLE
GM view for Skill Tree item in Foundry

### ISSUE THREAD

**Issue by DenDrummer** [DenDrummer/classless-skill-tree-5e#4]
An actual item that can be added to a character sheet.

***TO-DO:***
- [x] skill tree template file
   - [ ] new node button in skill tree
   - [ ] scrollable canvas to see nodes
   - [ ] click on node to open node details
- [ ] skill node template file
   - [ ] coordinate inputs
   - [ ] id input
   - [ ] title input
   - [ ] description input
   - [ ] parent IDs input (space separated?)
